version: "3"

services:
  web01:
    build: ./web1
    ports:
      - "5001:5000"

  web02:
    build: ./web2
    ports:
      - "5002:5000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web01
      - web02